import { Inter } from 'next/font/google';
import './globals.css';
import GlobalState from '@/context';
import Navbar from '@/components/Navbar';
import Login from './login/page';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const dynamic = 'force-dynamic';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalState>
          <Navbar />
          <main className="flex max-h-screen flex-col transition-all duration-200 ease-in-out">
            {children}
          </main>
        </GlobalState>
      </body>
    </html>
  );
}
